spring:
  mvc:
    format:
      date: dd-MM-yyyy
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
